name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore MottuFlowDotNet/*.csproj

      - name: Build
        run: dotnet build MottuFlowDotNet/*.csproj --no-restore

      - name: Test
        run: dotnet test MottuFlowDotNet/*.csproj --no-build --verbosity normal

      # --- Passo SonarCloud ---
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectKey: leomotalima_MottuFlowDotNet
          organization: leomotalima
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
