name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner for MSBuild
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud Analysis
        run: dotnet sonarscanner begin /k:"MottuFlowDotNet" /o:"SUA_ORG_KEY_AQUI" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Restore dependencies
        run: dotnet restore MottuFlowDotNet/**/*.csproj

      - name: Build
        run: dotnet build MottuFlowDotNet/**/*.csproj --no-restore

      - name: End SonarCloud Analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
